version: '3'
services:
  # https://github.com/clue/docker-json-server
  db-mock:
    image: zhenik/json-server
    environment:
      - ID_MAP=id
    ports:
      - "3000:80"
    volumes:
      - ./database.json:/data/db.json